# 基础知识

## 列表属性

In [1]:
import numpy as np

导入numpy第三方库

In [8]:
arr=np.arange(30)

此处先创建一个数列，供后面使用方便

In [9]:
arr.ndim

1

ndim属性，显示数组的维度数量

In [10]:
arr.shape

(30,)

shape属性，显示数组的维度，再如下

In [11]:
arr.size

30

size属性，显示数组的大小

In [12]:
arr.dtype

dtype('int32')

dtype属性，显示数组中的数据类型

In [13]:
arr.itemsize

4

itemsize属性，显示数组中元素的字节大小

In [14]:
arr.data

我们一般不使用这个属性

## 数组创建

### 1.从原始的python中的列表或元组中创建数组

In [2]:
import numpy as np

In [3]:
np.array([1,2,3])

array([1, 2, 3])

In [4]:
np.array((2,3,4))

array([2, 3, 4])

此处常见的错误是创建数组的时候直接传入数字参数

In [6]:
np.array(2,3,4) ## 这里是错的

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [8]:
np.array([[2,3],[4,5]])

array([[2, 3],
       [4, 5]])

还可以创建多维的数组

In [11]:
np.array([[2,3],[4,5]],dtype=float)

array([[2., 3.],
       [4., 5.]])

可以在创建数组的时候预设元素类型

### 2.创建占位符的元素

对于一些已知数组的大小，但是对具体的内容还不确定的数组，可以通过几个函数先创建具有初始占位符的数组

In [12]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.zeros([2,1])

array([[0.],
       [0.]])

In [18]:
np.empty([3,3])

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 8.08291397e-321],
       [1.97345609e-312, 1.24610383e-306, 3.17320232e-317]])

empty创建的是具有随机初始值的数组

### 3.创建数字数组

In [20]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [21]:
np.arange(5)

array([0, 1, 2, 3, 4])

上面是两种比较简单的创建方法

In [23]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [24]:
np.arange(0,2,0.5)

array([0. , 0.5, 1. , 1.5])

上面两种可以设定元素间的间隔大小

arange函数终究在float元素类型无法预测所获得元素的数量，可以使用linspace这一函数

In [1]:
np.linspace(0,2,9)

NameError: name 'np' is not defined

如此可以直接确定创建的数组中的元素数量

## 数组打印

In [2]:
print(array)

NameError: name 'array' is not defined

可以直接通过print语句来输出数组

## 基本操作

In [3]:
import numpy as np

In [5]:
a=np.array([20,30,40,40])

In [6]:
b=np.arange(4)

In [8]:
b

array([0, 1, 2, 3])

In [10]:
c=a-b

In [11]:
c

array([20, 29, 38, 37])

减法操作在两个数组形状相同的情况下，可以实现一对一的减法

In [13]:
b**2

array([0, 1, 4, 9], dtype=int32)

In [14]:
b*a

array([  0,  30,  80, 120])

乘法对于直接乘以一个常数和两个数组相乘都可以起到作用

In [15]:
A=np.array([[1,1],[0,1]])

In [16]:
B=np.array([[2,0],[3,4]])

In [17]:
A*B

array([[2, 0],
       [0, 4]])

In [18]:
A@B

array([[5, 4],
       [3, 4]])

In [19]:
A.dot(B)

array([[5, 4],
       [3, 4]])

矩阵乘法可以通过@或者dot方法来实现

In [20]:
a=np.ones([2,3],dtype=int)

In [23]:
a*=3

In [24]:
a

array([[27, 27, 27],
       [27, 27, 27]])

有些运算符，比如*=或者+=会直接修改被操作的数组而不会产生新的数组